#Requires -Version 5.1
# install-hooks.ps1 - Install git hooks for this project
#
# Creates a cross-platform pre-commit hook that runs validate.ps1 on Windows
# and validate.sh on Unix.
#
# Usage: .\scripts\install-hooks.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir
$HookPath = Join-Path $ProjectDir '.git\hooks\pre-commit'

# Write a bash shim that detects OS and runs the right validator.
# Git for Windows runs hooks through its bundled MINGW bash, so the hook
# file must be a valid shell script even on Windows.
$hookContent = @'
#!/bin/sh
# Auto-generated by install-hooks.ps1
# Runs validate.ps1 on Windows (Git Bash), validate.sh on Unix
HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPTS_DIR="$HOOK_DIR/../../scripts"

case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$SCRIPTS_DIR/validate.ps1"
        exit $?
        ;;
    *)
        exec "$SCRIPTS_DIR/validate.sh"
        ;;
esac
'@

# Ensure hooks directory exists
$hooksDir = Split-Path -Parent $HookPath
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
}

Set-Content -Path $HookPath -Value $hookContent -Encoding ASCII -NoNewline
Write-Host "Installed pre-commit hook (runs validate.ps1 on Windows, validate.sh on Unix)"
